<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$tabs = array( 'dashboard' => 'داشبورد کارکنان', 'daily_reports' => 'گزارش روزانه', 'requests' => 'درخواست از مدیریت', 'issues' => 'مشکلات و موانع', 'tasks' => 'وظایف', 'announcements' => 'اطلاعیه‌ها' );
$report_statuses = array( 'submitted' => 'ارسال شده', 'seen' => 'دیده شد', 'responded' => 'پاسخ داده شد', 'closed' => 'بسته شد' );
$request_statuses = array( 'new' => 'جدید', 'seen' => 'دیده شد', 'in_review' => 'در حال بررسی', 'done' => 'انجام شد', 'rejected' => 'رد شد' );
$issue_statuses = array( 'new' => 'جدید', 'seen' => 'دیده شد', 'in_review' => 'در حال بررسی', 'resolved' => 'حل شد', 'rejected' => 'رد شد' );
$task_statuses = array( 'new' => 'جدید', 'in_progress' => 'در حال انجام', 'done' => 'انجام شد', 'blocked' => 'متوقف شده', 'cancelled' => 'لغو شد' );
$employee_task_statuses = array_diff_key( $task_statuses, array( 'cancelled' => true ) );
$priorities = array( 'low' => 'کم', 'normal' => 'معمولی', 'high' => 'زیاد' );
$severities = array( 'low' => 'کم', 'medium' => 'متوسط', 'high' => 'زیاد' );
$categories = array( 'manager_decision' => 'نیاز به تصمیم مدیر', 'purchase_or_supply' => 'نیاز به خرید یا تأمین', 'customer_problem' => 'مشکل با مشتری', 'internal_process_problem' => 'مشکل فرایندی داخلی', 'improvement_suggestion' => 'پیشنهاد بهبود', 'error_or_bug_report' => 'گزارش خطا یا مشکل', 'other' => 'سایر' );
$audiences = array( 'all' => 'همه کارکنان', 'selected_roles' => 'نقش‌های منتخب', 'selected_users' => 'کاربران منتخب' );
$role_labels = array( 'sales_agent' => 'کارشناس فروش', 'sales_manager' => 'مدیر فروش', 'internal_employee' => 'کارمند داخلی', 'crm_admin' => 'مدیر CRM', 'administrator' => 'مدیر کل' );
$notice_labels = array( 'saved' => 'اطلاعات با موفقیت ذخیره شد.', 'access_denied' => 'شما اجازه انجام این عملیات را ندارید.', 'validation_error' => 'لطفاً فیلدهای الزامی گزارش فروش را تکمیل کنید.', 'attachment_upload_failed' => 'بارگذاری فایل انجام نشد.' );
$sales_stat_labels = $sales_stats_service->get_labels();
$sales_form_keys = array( 'claimed_today', 'current_owned_requests', 'actions_today', 'call_answered_today', 'call_no_answer_today', 'whatsapp_sent_today', 'internal_notes_today', 'followups_scheduled_today', 'followups_due_today', 'overdue_followups', 'won_today', 'lost_today', 'invalid_today', 'open_requests', 'closed_today' );
$sales_snapshot_keys = array( 'claimed_today', 'actions_today', 'call_answered_today', 'call_no_answer_today', 'whatsapp_sent_today', 'followups_due_today', 'overdue_followups', 'won_today', 'lost_today', 'invalid_today', 'open_requests', 'generated_at' );
$user_label = function( $id ) { $user = get_userdata( absint( $id ) ); return $user ? $user->display_name : 'کاربر حذف‌شده'; };
$badge = function( $value, $labels ) { return '<span class="crpcrm-badge crpcrm-status-badge crpcrm-status-' . esc_attr( $value ) . '">' . esc_html( $labels[ $value ] ?? $value ) . '</span>'; };
$detail_url = function( $item_id ) use ( $tab ) { return add_query_arg( array( 'page' => 'crpcrm-staff', 'staff_tab' => $tab, 'staff_item_id' => absint( $item_id ) ), admin_url( 'admin.php' ) ); };
$list_url = add_query_arg( array( 'page' => 'crpcrm-staff', 'staff_tab' => $tab ), admin_url( 'admin.php' ) );
$announcement_data = $detail_item && 'announcements' === $tab ? CRPCRM_Helpers::maybe_json_decode( $detail_item['audience_data'], true ) : array();
?>
<div class="wrap crpcrm-admin-wrap crpcrm-staff-admin" dir="rtl">
<h1>پنل کارکنان</h1>
<p class="description">نمای عملیاتی روزانه برای گزارش‌ها، درخواست‌ها، وظایف، مشکلات و اطلاعیه‌ها.</p>
<?php if ( $notice && isset( $notice_labels[ $notice ] ) ) : ?><div class="notice <?php echo 'saved' === $notice ? 'notice-success' : 'notice-error'; ?> is-dismissible"><p><?php echo esc_html( $notice_labels[ $notice ] ); ?></p></div><?php endif; ?>
<nav class="nav-tab-wrapper"><?php foreach ( $tabs as $key => $label ) : ?><a class="nav-tab <?php echo $tab === $key ? 'nav-tab-active' : ''; ?>" href="<?php echo esc_url( add_query_arg( array( 'page' => 'crpcrm-staff', 'staff_tab' => $key ), admin_url( 'admin.php' ) ) ); ?>"><?php echo esc_html( $label ); ?></a><?php endforeach; ?></nav>

<?php if ( 'dashboard' === $tab ) : ?>
<div class="crpcrm-kpi-grid crpcrm-staff-kpi-grid">
<div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['open_tasks'] ); ?></span><span class="crpcrm-stat-label">وظایف باز من</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['overdue_tasks'] ); ?></span><span class="crpcrm-stat-label">وظایف عقب‌افتاده من</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['unread_announcements'] ); ?></span><span class="crpcrm-stat-label">اطلاعیه‌های خوانده‌نشده</span></div>
<?php if ( ! $can_manage ) : ?><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['today_report'] ); ?></span><span class="crpcrm-stat-label">گزارش امروز من</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['open_requests'] ); ?></span><span class="crpcrm-stat-label">درخواست‌های باز من</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['customer_replies'] ?? 0 ); ?></span><span class="crpcrm-stat-label">پاسخ جدید مشتری</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['lead_follow_ups'] ?? 0 ); ?></span><span class="crpcrm-stat-label">پیگیری خودکار ۲۴ ساعته</span></div><?php endif; ?>
</div>
<?php if ( $can_manage ) : ?><div class="crpcrm-kpi-grid crpcrm-staff-kpi-grid"><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( count( $dashboard_counts['reported_users'] ) ); ?></span><span class="crpcrm-stat-label">گزارش‌های امروز</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['attention_reports'] ); ?></span><span class="crpcrm-stat-label">گزارش نیازمند توجه</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['new_requests'] ); ?></span><span class="crpcrm-stat-label">درخواست جدید</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['unassigned_requests'] ?? 0 ); ?></span><span class="crpcrm-stat-label">درخواست‌های بدون مسئول</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['customer_replies'] ?? 0 ); ?></span><span class="crpcrm-stat-label">پاسخ جدید مشتری</span></div><div class="crpcrm-stat-card"><span class="crpcrm-stat-value"><?php echo esc_html( $dashboard_counts['lead_follow_ups'] ?? 0 ); ?></span><span class="crpcrm-stat-label">پیگیری خودکار ۲۴ ساعته</span></div></div>
<div class="crpcrm-card"><h2>خلاصه فروش امروز</h2><div class="crpcrm-table-wrap crpcrm-table-scroll"><table class="widefat striped"><thead><tr><th>کارشناس</th><th>گزارش</th><th>اقدامات</th><th>تماس پاسخ داده</th><th>پیگیری عقب‌افتاده</th><th>موفق</th><th>ناموفق</th></tr></thead><tbody><?php foreach ( $dashboard_counts['sales_today_summary'] as $row ) : $stats = $row['stats']; ?><tr><td><?php echo esc_html( $row['display_name'] ); ?></td><td><?php echo esc_html( $row['reported_today'] ? 'ثبت شده' : 'ثبت نشده' ); ?></td><td><?php echo esc_html( absint( $stats['actions_today'] ?? 0 ) ); ?></td><td><?php echo esc_html( absint( $stats['call_answered_today'] ?? 0 ) ); ?></td><td><?php echo esc_html( absint( $stats['overdue_followups'] ?? 0 ) ); ?></td><td><?php echo esc_html( absint( $stats['won_today'] ?? 0 ) ); ?></td><td><?php echo esc_html( absint( $stats['lost_today'] ?? 0 ) ); ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<?php endif; ?>

<?php if ( $detail_item ) : ?>
<div class="crpcrm-card crpcrm-staff-detail"><div class="crpcrm-detail-heading"><h2>مشاهده جزئیات</h2><a class="button" href="<?php echo esc_url( $list_url ); ?>">بازگشت به فهرست</a></div>
<?php if ( 'daily_reports' === $tab ) : $snapshot = $sales_stats_service->decode_snapshot( $detail_item['sales_crm_snapshot'] ?? '' ); ?>
<dl class="crpcrm-detail-list"><dt>کارمند</dt><dd><?php echo esc_html( $user_label( $detail_item['user_id'] ) ); ?></dd><dt>تاریخ گزارش</dt><dd><?php echo esc_html( CRPCRM_Helpers::format_jalali_date( $detail_item['report_date'] ) ); ?></dd><dt>کارهای انجام‌شده</dt><dd><?php echo nl2br( esc_html( $detail_item['completed_work'] ) ); ?></dd><dt>کارهای نیمه‌تمام</dt><dd><?php echo nl2br( esc_html( $detail_item['unfinished_work'] ) ); ?></dd><dt>مشکلات</dt><dd><?php echo nl2br( esc_html( $detail_item['problems'] ) ); ?></dd><dt>برنامه فردا</dt><dd><?php echo nl2br( esc_html( $detail_item['tomorrow_plan'] ) ); ?></dd><?php if ( ! empty( $detail_item['sales_comment'] ) ) : ?><dt>توضیح تکمیلی فروش</dt><dd><?php echo nl2br( esc_html( $detail_item['sales_comment'] ) ); ?></dd><?php endif; ?><?php if ( ! empty( $detail_item['manager_response'] ) ) : ?><dt>پاسخ مدیر</dt><dd><?php echo nl2br( esc_html( $detail_item['manager_response'] ) ); ?></dd><?php endif; ?></dl>
<?php if ( $snapshot ) : ?><h3>آمار CRM در زمان ارسال گزارش</h3><div class="crpcrm-detail-stats"><?php foreach ( $sales_snapshot_keys as $key ) : ?><div><span><?php echo esc_html( $sales_stat_labels[ $key ] ?? $key ); ?></span><strong><?php echo esc_html( 'generated_at' === $key ? CRPCRM_Helpers::format_jalali_datetime( $snapshot[ $key ] ) : absint( $snapshot[ $key ] ?? 0 ) ); ?></strong></div><?php endforeach; ?></div><?php endif; ?>
<?php if ( $can_manage ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_manage_daily_report' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="manage_daily_report"><input type="hidden" name="report_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><select name="manager_action"><option value="seen">دیده شد</option><option value="responded">پاسخ داده شد</option><option value="closed">بسته شد</option></select><textarea name="manager_response" rows="3" class="large-text" placeholder="پاسخ مدیریتی"><?php echo esc_textarea( $detail_item['manager_response'] ); ?></textarea><?php submit_button( 'ثبت پاسخ و وضعیت' ); ?></form><?php endif; ?>
<?php elseif ( 'requests' === $tab ) : ?>
<?php $request_attachment_html = CRPCRM_Dynamic_Form_Renderer::render_uploaded_file_value( $detail_item['request_attachment'] ?? '', array( 'source_type' => 'staff_request', 'source_id' => absint( $detail_item['id'] ?? 0 ), 'source_field' => 'request_attachment' ), 'admin' ); $manager_response_attachment_html = CRPCRM_Dynamic_Form_Renderer::render_uploaded_file_value( $detail_item['manager_response_attachment'] ?? '', array( 'source_type' => 'staff_request', 'source_id' => absint( $detail_item['id'] ?? 0 ), 'source_field' => 'manager_response_attachment' ), 'admin' ); ?>
<dl class="crpcrm-detail-list">
<dt>کارمند</dt><dd><?php echo esc_html( $user_label( $detail_item['user_id'] ) ); ?></dd>
<dt>عنوان</dt><dd><?php echo esc_html( $detail_item['title'] ); ?></dd>
<dt>دسته‌بندی</dt><dd><?php echo esc_html( $categories[ $detail_item['category'] ] ?? $detail_item['category'] ); ?></dd>
<dt>شرح کامل</dt><dd><?php echo nl2br( esc_html( $detail_item['description'] ) ); ?></dd>
<?php if ( $request_attachment_html ) : ?><dt>پیوست فایل</dt><dd><?php echo $request_attachment_html; ?></dd><?php endif; ?>
<dt>وضعیت</dt><dd><?php echo $badge( $detail_item['status'], $request_statuses ); ?></dd>
<?php if ( ! empty( $detail_item['manager_response'] ) || $manager_response_attachment_html ) : ?><dt>پاسخ مدیر</dt><dd><?php if ( ! empty( $detail_item['manager_response'] ) ) : ?><div class="crpcrm-staff-response-text"><?php echo nl2br( esc_html( $detail_item['manager_response'] ) ); ?></div><?php endif; ?><?php if ( $manager_response_attachment_html ) : ?><div class="crpcrm-staff-response-attachment"><?php echo $manager_response_attachment_html; ?></div><?php endif; ?></dd><?php endif; ?>
</dl>
<?php if ( $can_manage ) : ?><form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_manage_staff_request' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="manage_staff_request"><input type="hidden" name="request_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><select name="status"><?php foreach ( $request_statuses as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $detail_item['status'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><textarea name="manager_response" rows="4" class="large-text" placeholder="پاسخ مدیر"><?php echo esc_textarea( $detail_item['manager_response'] ); ?></textarea><div class="crpcrm-staff-upload-field"><label><?php echo esc_html( 'پیوست فایل' ); ?></label><?php echo CRPCRM_Dynamic_Form_Renderer::render_file_upload_field( 'manager_response_attachment' ); ?></div><?php submit_button( 'ثبت پاسخ و وضعیت' ); ?></form><?php endif; ?>
<?php elseif ( 'issues' === $tab ) : ?>
<dl class="crpcrm-detail-list"><dt>کارمند</dt><dd><?php echo esc_html( $user_label( $detail_item['user_id'] ) ); ?></dd><dt>عنوان</dt><dd><?php echo esc_html( $detail_item['title'] ); ?></dd><dt>واحد مرتبط</dt><dd><?php echo esc_html( $detail_item['related_department'] ); ?></dd><dt>شرح کامل مشکل</dt><dd><?php echo nl2br( esc_html( $detail_item['description'] ) ); ?></dd><dt>راهکار پیشنهادی</dt><dd><?php echo nl2br( esc_html( $detail_item['suggested_solution'] ) ); ?></dd><dt>وضعیت</dt><dd><?php echo $badge( $detail_item['status'], $issue_statuses ); ?></dd><?php if ( $detail_item['manager_response'] ) : ?><dt>پاسخ مدیر</dt><dd><?php echo nl2br( esc_html( $detail_item['manager_response'] ) ); ?></dd><?php endif; ?></dl>
<?php if ( $can_manage ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_manage_issue' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="manage_issue"><input type="hidden" name="issue_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><select name="status"><?php foreach ( $issue_statuses as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $detail_item['status'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><textarea name="manager_response" rows="4" class="large-text" placeholder="پاسخ مدیر"><?php echo esc_textarea( $detail_item['manager_response'] ); ?></textarea><?php submit_button( 'ثبت پاسخ و وضعیت' ); ?></form><?php endif; ?>
<?php elseif ( 'tasks' === $tab ) : ?>
<dl class="crpcrm-detail-list"><dt>عنوان</dt><dd><?php echo esc_html( $detail_item['title'] ); ?></dd><dt>شرح کامل وظیفه</dt><dd><?php echo nl2br( esc_html( $detail_item['description'] ) ); ?></dd><dt>مسئول</dt><dd><?php echo esc_html( $user_label( $detail_item['assigned_to'] ) ); ?></dd><dt>مهلت</dt><dd><?php echo esc_html( CRPCRM_Helpers::format_jalali_date( $detail_item['due_date'] ) ); ?></dd><dt>وضعیت</dt><dd><?php echo $badge( $detail_item['status'], $task_statuses ); ?></dd><?php if ( $detail_item['employee_update'] ) : ?><dt>گزارش کارمند</dt><dd><?php echo nl2br( esc_html( $detail_item['employee_update'] ) ); ?></dd><?php endif; ?><?php if ( $detail_item['manager_note'] ) : ?><dt>یادداشت مدیر</dt><dd><?php echo nl2br( esc_html( $detail_item['manager_note'] ) ); ?></dd><?php endif; ?></dl>
<?php if ( $can_manage ) : ?><h3>ویرایش وظیفه</h3><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_save_task' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="save_task"><input type="hidden" name="task_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><p><input name="title" required class="regular-text" value="<?php echo esc_attr( $detail_item['title'] ); ?>"></p><p><textarea name="description" required rows="5" class="large-text"><?php echo esc_textarea( $detail_item['description'] ); ?></textarea></p><p><select name="assigned_to"><?php foreach ( $staff_users as $user ) : ?><option value="<?php echo esc_attr( $user->ID ); ?>" <?php selected( $detail_item['assigned_to'], $user->ID ); ?>><?php echo esc_html( $user->display_name ); ?></option><?php endforeach; ?></select> <?php echo CRPCRM_Helpers::jalali_date_input( 'due_date', $detail_item['due_date'] ); ?> <select name="priority"><?php foreach ( $priorities as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $detail_item['priority'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><select name="status"><?php foreach ( $task_statuses as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $detail_item['status'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></p><textarea name="manager_note" rows="3" class="large-text" placeholder="یادداشت مدیر"><?php echo esc_textarea( $detail_item['manager_note'] ); ?></textarea><?php submit_button( 'ذخیره وظیفه' ); ?></form>
<?php else : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_update_task_status' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="update_task_status"><input type="hidden" name="task_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><select name="status"><?php foreach ( $employee_task_statuses as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $detail_item['status'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><textarea name="note" rows="3" class="large-text" placeholder="گزارش انجام وظیفه"><?php echo esc_textarea( $detail_item['employee_update'] ); ?></textarea><?php submit_button( 'ثبت وضعیت وظیفه' ); ?></form><?php endif; ?>
<?php elseif ( 'announcements' === $tab ) : ?>
<dl class="crpcrm-detail-list"><dt>عنوان</dt><dd><?php echo esc_html( $detail_item['title'] ); ?></dd><dt>متن اطلاعیه</dt><dd><?php echo nl2br( esc_html( $detail_item['body'] ) ); ?></dd><dt>تاریخ ایجاد</dt><dd><?php echo esc_html( CRPCRM_Helpers::format_jalali_datetime( $detail_item['created_at'] ) ); ?></dd></dl>
<?php if ( $can_manage ) : $stats = $repository->get_announcement_read_stats( $detail_item['id'] ); ?><p><strong>دیده‌اند:</strong> <?php echo esc_html( implode( '، ', array_map( $user_label, $stats['seen_ids'] ) ) ?: 'هیچ‌کس' ); ?></p><p><strong>ندیده‌اند:</strong> <?php echo esc_html( implode( '، ', array_map( $user_label, $stats['unseen_ids'] ) ) ?: 'هیچ‌کس' ); ?></p><h3>ویرایش اطلاعیه</h3><?php endif; ?>
<?php if ( ! $can_manage && ! $repository->user_has_read_announcement( $detail_item['id'], get_current_user_id() ) ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_mark_announcement_read' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="mark_announcement_read"><input type="hidden" name="announcement_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><?php submit_button( 'علامت‌گذاری به‌عنوان مشاهده‌شده' ); ?></form><?php endif; ?>
<?php if ( $can_manage ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_save_announcement' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="save_announcement"><input type="hidden" name="announcement_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><p><input name="title" required class="regular-text" value="<?php echo esc_attr( $detail_item['title'] ); ?>"></p><p><textarea name="body" required rows="6" class="large-text"><?php echo esc_textarea( $detail_item['body'] ); ?></textarea></p><p><select name="audience_type"><?php foreach ( $audiences as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $detail_item['audience_type'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></p><p><?php foreach ( $role_labels as $key => $label ) : ?><label><input type="checkbox" name="audience_roles[]" value="<?php echo esc_attr( $key ); ?>" <?php checked( is_array( $announcement_data ) && in_array( $key, $announcement_data, true ) ); ?>> <?php echo esc_html( $label ); ?></label> <?php endforeach; ?></p><p><?php foreach ( $staff_users as $user ) : ?><label><input type="checkbox" name="audience_users[]" value="<?php echo esc_attr( $user->ID ); ?>" <?php checked( is_array( $announcement_data ) && in_array( absint( $user->ID ), array_map( 'absint', $announcement_data ), true ) ); ?>> <?php echo esc_html( $user->display_name ); ?></label> <?php endforeach; ?></p><?php submit_button( 'ذخیره تغییرات' ); ?></form><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" onsubmit="return confirm('اطلاعیه حذف شود؟');"><?php wp_nonce_field( 'crpcrm_staff_delete_announcement' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="delete_announcement"><input type="hidden" name="announcement_id" value="<?php echo esc_attr( $detail_item['id'] ); ?>"><?php submit_button( 'حذف اطلاعیه', 'delete' ); ?></form><?php endif; ?>
<?php endif; ?></div>
<?php endif; ?>

<?php if ( 'daily_reports' === $tab && ! $can_manage ) : ?><div class="crpcrm-card"><h2><?php echo $today_report ? 'ویرایش گزارش امروز' : 'ثبت گزارش روزانه'; ?></h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_save_daily_report' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="save_daily_report"><?php if ( $is_sales_user ) : ?><h3>آمار امروز شما در CRM</h3><div class="crpcrm-detail-stats"><?php foreach ( $sales_form_keys as $key ) : ?><div><span><?php echo esc_html( $sales_stat_labels[ $key ] ?? $key ); ?></span><strong><?php echo esc_html( absint( $current_sales_stats[ $key ] ?? 0 ) ); ?></strong></div><?php endforeach; ?></div><?php endif; ?><p><textarea name="completed_work" required rows="4" class="large-text" placeholder="کارهای انجام‌شده امروز"><?php echo esc_textarea( $today_report['completed_work'] ?? '' ); ?></textarea></p><p><textarea name="unfinished_work" required rows="4" class="large-text" placeholder="کارهای نیمه‌تمام"><?php echo esc_textarea( $today_report['unfinished_work'] ?? '' ); ?></textarea></p><p><textarea name="problems" required rows="4" class="large-text" placeholder="مشکلات امروز"><?php echo esc_textarea( $today_report['problems'] ?? '' ); ?></textarea></p><p><textarea name="tomorrow_plan" required rows="4" class="large-text" placeholder="برنامه فردا"><?php echo esc_textarea( $today_report['tomorrow_plan'] ?? '' ); ?></textarea></p><label><input type="checkbox" name="needs_manager_attention" <?php checked( ! empty( $today_report['needs_manager_attention'] ) ); ?>> نیاز به توجه مدیر</label><?php if ( $is_sales_user ) : ?><p><textarea name="sales_comment" required rows="4" class="large-text" placeholder="توضیح تکمیلی فروش"><?php echo esc_textarea( $today_report['sales_comment'] ?? '' ); ?></textarea></p><?php endif; ?><?php submit_button( 'ثبت گزارش روزانه' ); ?></form></div><?php endif; ?>

<?php if ( in_array( $tab, array( 'requests', 'issues' ), true ) && ! $can_manage ) : ?><div class="crpcrm-card"><h2><?php echo 'requests' === $tab ? 'ثبت درخواست از مدیریت' : 'ثبت مشکل یا مانع'; ?></h2><form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_' . ( 'requests' === $tab ? 'save_staff_request' : 'save_issue' ) ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="<?php echo 'requests' === $tab ? 'save_staff_request' : 'save_issue'; ?>"><?php if ( 'requests' === $tab ) : ?><p><select name="category"><?php foreach ( $categories as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select> <select name="priority"><?php foreach ( $priorities as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></p><div class="crpcrm-staff-upload-field"><label><?php echo esc_html( 'پیوست فایل' ); ?></label><?php echo CRPCRM_Dynamic_Form_Renderer::render_file_upload_field( 'request_attachment' ); ?></div><?php else : ?><p><input name="related_department" required placeholder="واحد مرتبط"> <select name="severity"><?php foreach ( $severities as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></p><?php endif; ?><p><input name="title" required class="regular-text" placeholder="عنوان"></p><p><textarea name="description" required rows="5" class="large-text" placeholder="شرح کامل"></textarea></p><?php if ( 'issues' === $tab ) : ?><p><textarea name="suggested_solution" rows="3" class="large-text" placeholder="راهکار پیشنهادی"></textarea></p><label><input type="checkbox" name="needs_manager_decision"> نیازمند تصمیم مدیر</label><?php endif; ?><?php submit_button( 'ثبت' ); ?></form></div><?php endif; ?>

<?php if ( 'tasks' === $tab && $can_manage && ! $detail_item ) : ?><div class="crpcrm-card"><h2>ایجاد وظیفه</h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_save_task' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="save_task"><p><input name="title" required class="regular-text" placeholder="عنوان وظیفه"></p><p><textarea name="description" required rows="4" class="large-text" placeholder="شرح وظیفه"></textarea></p><p><select name="assigned_to"><?php foreach ( $staff_users as $user ) : ?><option value="<?php echo esc_attr( $user->ID ); ?>"><?php echo esc_html( $user->display_name ); ?></option><?php endforeach; ?></select> <?php echo CRPCRM_Helpers::jalali_date_input( 'due_date', '' ); ?> <select name="priority"><?php foreach ( $priorities as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><input type="hidden" name="status" value="new"></p><?php submit_button( 'ایجاد وظیفه' ); ?></form></div><?php endif; ?>

<?php if ( 'announcements' === $tab && $can_manage && ! $detail_item ) : ?><div class="crpcrm-card"><h2>ثبت اطلاعیه</h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'crpcrm_staff_save_announcement' ); ?><input type="hidden" name="action" value="crpcrm_staff_action"><input type="hidden" name="staff_action_type" value="save_announcement"><p><input name="title" required class="regular-text" placeholder="عنوان"></p><p><textarea name="body" required rows="5" class="large-text" placeholder="متن اطلاعیه"></textarea></p><p><select name="audience_type"><?php foreach ( $audiences as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></p><p><?php foreach ( $role_labels as $key => $label ) : ?><label><input type="checkbox" name="audience_roles[]" value="<?php echo esc_attr( $key ); ?>"> <?php echo esc_html( $label ); ?></label> <?php endforeach; ?></p><p><?php foreach ( $staff_users as $user ) : ?><label><input type="checkbox" name="audience_users[]" value="<?php echo esc_attr( $user->ID ); ?>"> <?php echo esc_html( $user->display_name ); ?></label> <?php endforeach; ?></p><?php submit_button( 'ثبت اطلاعیه' ); ?></form></div><?php endif; ?>

<?php if ( 'dashboard' !== $tab ) : ?>
<?php $filter_file = __DIR__ . '/staff-parts/filters-' . ( 'daily_reports' === $tab ? 'daily' : $tab ) . '.php'; if ( file_exists( $filter_file ) ) { include $filter_file; } ?>
<div class="crpcrm-table-wrap crpcrm-table-scroll"><table class="widefat striped crpcrm-staff-list"><thead><tr>
<?php if ( 'daily_reports' === $tab ) : ?><th>تاریخ</th><th>کارمند</th><th>وضعیت</th><th>نیازمند توجه</th>
<?php elseif ( 'requests' === $tab ) : ?><th>عنوان</th><th>کارمند</th><th>دسته‌بندی</th><th>اولویت</th><th>وضعیت</th>
<?php elseif ( 'issues' === $tab ) : ?><th>عنوان</th><th>کارمند</th><th>واحد مرتبط</th><th>شدت</th><th>وضعیت</th>
<?php elseif ( 'tasks' === $tab ) : ?><th>عنوان</th><th>مسئول</th><th>مهلت</th><th>اولویت</th><th>وضعیت</th>
<?php else : ?><th>عنوان</th><?php if ( $can_manage ) : ?><th>مخاطب</th><th>ایجادکننده</th><th>تعداد مشاهده</th><?php endif; ?><th>تاریخ ایجاد</th><?php endif; ?><th>عملیات</th></tr></thead><tbody>
<?php foreach ( $items as $item ) : ?><tr>
<?php if ( 'daily_reports' === $tab ) : ?><td><?php echo esc_html( CRPCRM_Helpers::format_jalali_date( $item['report_date'] ) ); ?></td><td><?php echo esc_html( $user_label( $item['user_id'] ) ); ?></td><td><?php echo $badge( $item['status'], $report_statuses ); ?></td><td><?php echo esc_html( $item['needs_manager_attention'] ? 'بله' : 'خیر' ); ?></td>
<?php elseif ( 'requests' === $tab ) : ?><td><strong><?php echo esc_html( $item['title'] ); ?></strong></td><td><?php echo esc_html( $user_label( $item['user_id'] ) ); ?></td><td><?php echo esc_html( $categories[ $item['category'] ] ?? $item['category'] ); ?></td><td><?php echo $badge( $item['priority'], $priorities ); ?></td><td><?php echo $badge( $item['status'], $request_statuses ); ?></td>
<?php elseif ( 'issues' === $tab ) : ?><td><strong><?php echo esc_html( $item['title'] ); ?></strong></td><td><?php echo esc_html( $user_label( $item['user_id'] ) ); ?></td><td><?php echo esc_html( $item['related_department'] ); ?></td><td><?php echo $badge( $item['severity'], $severities ); ?></td><td><?php echo $badge( $item['status'], $issue_statuses ); ?></td>
<?php elseif ( 'tasks' === $tab ) : ?><td><strong><?php echo esc_html( $item['title'] ); ?></strong></td><td><?php echo esc_html( $user_label( $item['assigned_to'] ) ); ?></td><td><?php echo esc_html( CRPCRM_Helpers::format_jalali_date( $item['due_date'] ) ); ?></td><td><?php echo $badge( $item['priority'], $priorities ); ?></td><td><?php echo $badge( $item['status'], $task_statuses ); ?></td>
<?php else : $stats = $can_manage ? $repository->get_announcement_read_stats( $item['id'] ) : array(); ?><td><strong><?php echo esc_html( $item['title'] ); ?></strong></td><?php if ( $can_manage ) : ?><td><?php echo esc_html( $audiences[ $item['audience_type'] ] ?? $item['audience_type'] ); ?></td><td><?php echo esc_html( $user_label( $item['created_by'] ) ); ?></td><td><?php echo esc_html( $stats['seen'] . ' / ' . ( $stats['seen'] + $stats['unseen'] ) ); ?></td><?php endif; ?><td><?php echo esc_html( CRPCRM_Helpers::format_jalali_datetime( $item['created_at'] ) ); ?></td><?php endif; ?>
<td><a class="button" href="<?php echo esc_url( $detail_url( $item['id'] ) ); ?>">مشاهده جزئیات</a></td></tr><?php endforeach; ?><?php if ( empty( $items ) ) : ?><tr><td colspan="8">موردی یافت نشد.</td></tr><?php endif; ?></tbody></table></div>
<?php endif; ?>
</div>
